CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230626085131_initial', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "OrderHeaders" ALTER COLUMN "Date" TYPE timestamp;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230626090725_ChangeColumnType', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "OrderStatusHistory" ALTER COLUMN "Date" TYPE timestamp;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230626100545_typechange', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE TABLE "Users" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountID" text NULL,
    "UserID" integer NOT NULL DEFAULT 1000,
    "FirstName" text NULL,
    "LastName" text NULL,
    "ContactNumber" text NULL,
    "Email" text NULL,
    "Description" text NULL,
    "PositionInCompany" text NULL,
    "Password" text NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230630081422_usermodelchange1', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE TABLE "RetroBonusDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RetroBonusID" text NOT NULL,
    "Barcode" text NOT NULL,
    "MinimalPercent" numeric NULL,
    "PlanPercent" numeric NULL,
    "ManufacturerPercent" numeric NULL,
    CONSTRAINT "PK_RetroBonusDetails" PRIMARY KEY ("Id")
);

CREATE TABLE "RetroBonusHeaders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountID" text NOT NULL,
    "RetroBonusID" text NOT NULL,
    "DocumentNo" text NOT NULL,
    "SupplierID" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NULL,
    "Status" text NOT NULL,
    "Condition" text NOT NULL,
    "IsMarketing" boolean NOT NULL,
    "FundedByManufacturer" boolean NOT NULL,
    "MinimalPercent" numeric NULL,
    "PlanAmount" numeric NULL,
    "PlanPercent" numeric NULL,
    "ManufacturerPercent" numeric NULL,
    CONSTRAINT "PK_RetroBonusHeaders" PRIMARY KEY ("Id")
);

CREATE TABLE "RetroBonusPlanRanges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RetroBonusID" text NOT NULL,
    "RangeNo" text NULL,
    "RangeName" text NULL,
    "RangePercent" numeric NULL,
    CONSTRAINT "PK_RetroBonusPlanRanges" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230717091601_retrobonus', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "RetroBonusPlanRanges" ADD "RetroBonusHeaderId" integer NULL;

ALTER TABLE "RetroBonusDetails" ADD "RetroBonusHeaderId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_RetroBonusPlanRanges_RetroBonusHeaderId" ON "RetroBonusPlanRanges" ("RetroBonusHeaderId");

CREATE INDEX "IX_RetroBonusDetails_RetroBonusHeaderId" ON "RetroBonusDetails" ("RetroBonusHeaderId");

ALTER TABLE "RetroBonusDetails" ADD CONSTRAINT "FK_RetroBonusDetails_RetroBonusHeaders_RetroBonusHeaderId" FOREIGN KEY ("RetroBonusHeaderId") REFERENCES "RetroBonusHeaders" ("Id") ON DELETE CASCADE;

ALTER TABLE "RetroBonusPlanRanges" ADD CONSTRAINT "FK_RetroBonusPlanRanges_RetroBonusHeaders_RetroBonusHeaderId" FOREIGN KEY ("RetroBonusHeaderId") REFERENCES "RetroBonusHeaders" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230717114648_retrobonus2', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "InvoiceDetails" ADD "InvoiceHeaderID1" integer NULL;

CREATE INDEX "IX_InvoiceDetails_InvoiceHeaderID1" ON "InvoiceDetails" ("InvoiceHeaderID1");

ALTER TABLE "InvoiceDetails" ADD CONSTRAINT "FK_InvoiceDetails_InvoiceHeaders_InvoiceHeaderID1" FOREIGN KEY ("InvoiceHeaderID1") REFERENCES "InvoiceHeaders" ("ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230809084937_iinv', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "PriceList" ADD "LastPrice" numeric NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230810113923_price', '7.0.5');

COMMIT;

