// <auto-generated />
using System;
using Marlin.sqlite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marlin.sqlite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231110123604_exchangelog")]
    partial class exchangelog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("InvoiceHeader", b =>
                {
                    b.Property<string>("InvoiceID")
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaybillNumber")
                        .HasColumnType("text");

                    b.HasKey("InvoiceID");

                    b.ToTable("InvoiceHeaders");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.AccessProfiles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("ProfileID")
                        .HasColumnType("text");

                    b.Property<string>("ProfileName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AccessProfiles");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.AccessSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccessObject")
                        .HasColumnType("text");

                    b.Property<string>("Grant")
                        .HasColumnType("text");

                    b.Property<string>("ProfileID")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AccessSettings");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.AccountData", b =>
                {
                    b.Property<string>("LegalCode")
                        .HasColumnType("text");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("Buyer")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProductsCount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Supplier")
                        .HasColumnType("boolean");

                    b.HasKey("LegalCode");

                    b.ToTable("AccountData");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.AccountSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("BillingSettings")
                        .HasColumnType("text");

                    b.Property<string>("BuyerWS")
                        .HasColumnType("text");

                    b.Property<string>("SupplierWS")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Accounts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("Buyer")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LegalCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool>("Supplier")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Barcodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("ProductID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Catalogues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ConnectionSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<bool>("AsBuyer")
                        .HasColumnType("boolean");

                    b.Property<bool>("AsSupplier")
                        .HasColumnType("boolean");

                    b.Property<string>("ConnectedAccountID")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionStatus")
                        .HasColumnType("text");

                    b.Property<string>("PriceTypes")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ConnectionSettings");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ErrorCodes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ErrorCodes");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ExchangeLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("JsonBody")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ExchangeLog");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Invoices", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<string>("Package")
                        .HasColumnType("text");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JSONBody")
                        .HasColumnType("text");

                    b.Property<string>("MessageID")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverID")
                        .HasColumnType("text");

                    b.Property<string>("SenderID")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceHeaderID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderHeaderID")
                        .HasColumnType("text");

                    b.Property<string>("OrderHeadersOrderID")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeadersOrderID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderDetailsFront", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvoiceQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<bool>("RedStatus")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ReservedQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Barcode");

                    b.ToTable("frontDetails");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderFront", b =>
                {
                    b.Property<string>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Scheduled")
                        .HasColumnType("text");

                    b.Property<string>("Shop")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<string>("VendorID")
                        .HasColumnType("text");

                    b.HasKey("OrderID");

                    b.ToTable("frontOrders");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderHeaders", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SendStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StatusID")
                        .HasColumnType("numeric");

                    b.HasKey("OrderID");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StatusID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<int>("StatusID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusHistory");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderStatusResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusResults");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.PositionName", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PriceTypeID")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PositionName");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.PriceList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceType")
                        .HasColumnType("text");

                    b.Property<string>("RetailerID")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("PriceList");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ProductCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("CategoryID")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ParentFolder")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ProductsByCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("CategoryID")
                        .HasColumnType("text");

                    b.Property<string>("ProductID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductsByCategories");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RBFront", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PlanAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RetroBonusID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RetroPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RBFronts");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ManufacturerPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimalPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PlanPercent")
                        .HasColumnType("numeric");

                    b.Property<int?>("RetroBonusHeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("RetroBonusID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RetroBonusHeaderId");

                    b.ToTable("RetroBonusDetails");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FundedByManufacturer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMarketing")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ManufacturerPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimalPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PlanAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PlanPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("RetroBonusID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RetroBonusHeaders");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusPlanRanges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RangeName")
                        .HasColumnType("text");

                    b.Property<string>("RangeNo")
                        .HasColumnType("text");

                    b.Property<decimal?>("RangePercent")
                        .HasColumnType("numeric");

                    b.Property<int?>("RetroBonusHeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("RetroBonusID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RetroBonusHeaderId");

                    b.ToTable("RetroBonusPlanRanges");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusResultFront", b =>
                {
                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PurchaseAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RetroBonusID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RetroPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Stock")
                        .HasColumnType("numeric");

                    b.HasKey("Product");

                    b.ToTable("RetroBonusResults");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.SLAByCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("InTimeOrders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Orders")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("sLAByCategories");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.SLAByOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("InTimeOrders")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Shop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("sLAByOrders");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.SLAByProducts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("InTimeOrders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Orders")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("SLAByProducts");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.SLAByShops", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("DeliveredQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InTimeOrders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Orders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Shop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("SLAByShops");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.SLAByVendors", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InTimeOrders")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Orders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("SLAByVendors");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.ServiceLevels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal?>("DeliveredAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeliveredQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("InTimeOrders")
                        .HasColumnType("integer");

                    b.Property<string>("OrderDate")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("OrderedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OrderedQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("text");

                    b.Property<decimal?>("SLAByAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SLAByQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Shop")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ServiceLevels");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Shops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("GPS")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("ShopID")
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.StocksOfProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ShopID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductsStocks");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.UserInfo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRetail")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionInCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.UserPositions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("PositionID")
                        .HasColumnType("text");

                    b.Property<string>("PositionName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("UserPositions");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.UserSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ProfileID")
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AccountID")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PositionInCompany")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.invdetails", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvoiceQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OrderAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OrderQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RedStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Barcode");

                    b.ToTable("invdetails");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.invoicfront", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<string>("Shop")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<string>("VendorID")
                        .HasColumnType("text");

                    b.Property<string>("WaybillNumber")
                        .HasColumnType("text");

                    b.HasKey("OrderID");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.temTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("InvoiceDetail", b =>
                {
                    b.HasOne("InvoiceHeader", "InvoiceHeader")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceHeader");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderDetails", b =>
                {
                    b.HasOne("Marlin.sqlite.Models.OrderHeaders", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderHeadersOrderID");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusDetails", b =>
                {
                    b.HasOne("Marlin.sqlite.Models.RetroBonusHeader", "RetroBonusHeader")
                        .WithMany("Products")
                        .HasForeignKey("RetroBonusHeaderId");

                    b.Navigation("RetroBonusHeader");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusPlanRanges", b =>
                {
                    b.HasOne("Marlin.sqlite.Models.RetroBonusHeader", null)
                        .WithMany("PlanRanges")
                        .HasForeignKey("RetroBonusHeaderId");
                });

            modelBuilder.Entity("InvoiceHeader", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.OrderHeaders", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Marlin.sqlite.Models.RetroBonusHeader", b =>
                {
                    b.Navigation("PlanRanges");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
